# syntax: "propertyName=propertyValue"
# 1 property each line
# every character (even spaces!) are taken into account as propertyName or propertyValue
# "=" is the special delimiter
# examples (do not delete!) :
debug=azerty1234-!&.,
debugint=1354648413
debugfloat=3.1415926

# your config here :

# =============== INTERACTIVE TESTS ================
interactive_menu_test=false


# ===================== UTILS =======================
seed=0

# ================== SWING DISPLAY ==================

swing_display_scale=75
swing_display_detailed=true

# ===================== BLOONS ======================

red_bloon_initial_life=1
red_bloon_speed=0.02

blue_bloon_initial_life=2
blue_bloon_speed=0.03

green_bloon_initial_life=4
green_bloon_speed=0.05

# Yellow n'est pas imposé par le sujet, donc on garde un choix d'équipe
yellow_bloon_initial_life=4
yellow_bloon_speed=0.05


# =================== PROJECTILES ===================

dart_projectile_damage=1
dart_projectile_speed=0.06

sharp_dart_projectile_damage=2
sharp_dart_projectile_speed=0.06

very_sharp_dart_projectile_damage=4
very_sharp_dart_projectile_speed=0.06

needle_projectile_damage=1
needle_projectile_speed=0.09

# Sujet officiel : Bombe = 2 dégâts
bomb_projectile_damage=2
bomb_projectile_speed=0.05
bomb_projectile_range=1.5

extra_bomb_projectile_damage=2
extra_bomb_projectile_speed=0.06
extra_bomb_projectile_range=2.0

# Non précisé par le sujet : choix d'équipe
freeze_projectile_speed=0.04
freeze_projectile_range=2
freeze_projectile_duration_ticks=60

# Non précisé par le sujet : choix d'équipe
slow_projectile_speed=0.05
slow_projectile_range=1.0
slow_projectile_factor=0.2
slow_projectile_duration_ticks=10


# ===================== TURRETS =====================

# Singe fléchettes
dart_monkey_cost=200
dart_monkey_initial_range=2.0
dart_monkey_initial_cooldown=60

# Tourelle aiguilles
needle_monkey_cost=350
needle_monkey_initial_range=1.6
needle_monkey_initial_cooldown=72

# Singe sniper
sniper_monkey_cost=500
sniper_monkey_initial_range=3.4028235E38
sniper_monkey_initial_cooldown=120

# Tour bombes
canon_monkey_cost=600
canon_monkey_initial_range=3.0
canon_monkey_initial_cooldown=108

# Gorille
junky_monkey_cost=1200
junky_monkey_initial_range=4.0
junky_monkey_initial_cooldown=18

# Tour glace
freeze_monkey_cost=400
freeze_monkey_initial_range=2.0
freeze_monkey_initial_cooldown=90

# Tour ralentissement
slow_monkey_cost=500
slow_monkey_initial_range=2.0
slow_monkey_initial_cooldown=90


# ===================== UPGRADES =====================


turret_range_initial_upgrade_cost=150
turret_shooting_cooldown_initial_upgrade_cost=150
turret_projectile_initial_upgrade_cost=200


# ===================== FISHES =====================
fish=🐟
pufferfish=🐡
tropicalfish=🐠
